# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_calc_neib_prop <- function(ego_ID, neib_list, neib_attr) {
    .Call(`_netABM_cpp_calc_neib_prop`, ego_ID, neib_list, neib_attr)
}

cpp_move_same_ethnicity <- function(agent_profile, place_profile, neib_place_id) {
    .Call(`_netABM_cpp_move_same_ethnicity`, agent_profile, place_profile, neib_place_id)
}

neib8_rcpp <- function(mat, posit_ind, include_ego) {
    .Call(`_netABM_neib8_rcpp`, mat, posit_ind, include_ego)
}

select_draft <- function(x, size = 1L) {
    .Call(`_netABM_select_draft`, x, size)
}

subset_by_rowid <- function(df, row_ids) {
    .Call(`_netABM_subset_by_rowid`, df, row_ids)
}

